export const icons = {
  online: <span className="material-symbols-outlined text-blue-500" style={{ fontVariationSettings: '"FILL" 1' }}>globe</span>,
  onsite: <span className="material-symbols-outlined text-green-500" style={{ fontVariationSettings: '"FILL" 1' }}>school</span>,
  unknown: <span className="material-symbols-outlined text-slate-400" style={{ fontVariationSettings: '"FILL" 1' }}>question_mark</span>,
  warning: <span className="material-symbols-outlined text-amber-500" style={{ fontVariationSettings: '"FILL" 1' }}>warning</span>,
  person: <span className="material-symbols-outlined text-indigo-500" style={{ fontVariationSettings: '"FILL" 1' }}>person</span>,
  home: <span className="material-symbols-outlined text-purple-500" style={{ fontVariationSettings: '"FILL" 1' }}>home</span>,
  book: <span className="material-symbols-outlined text-blue-600" style={{ fontVariationSettings: '"FILL" 1' }}>book</span>,
  door: <span className="material-symbols-outlined text-teal-500" style={{ fontVariationSettings: '"FILL" 1' }}>door_open</span>,
  location: <span className="material-symbols-outlined text-red-500" style={{ fontVariationSettings: '"FILL" 1' }}>location_on</span>,
  teacher: <span className="material-symbols-outlined text-violet-500" style={{ fontVariationSettings: '"FILL" 1' }}>school</span>,
  lightbulb: <span className="material-symbols-outlined text-yellow-500" style={{ fontVariationSettings: '"FILL" 1' }}>lightbulb</span>,
  celebration: <span className="material-symbols-outlined text-pink-500" style={{ fontVariationSettings: '"FILL" 1' }}>celebration</span>,
  bolt: <span className="material-symbols-outlined text-amber-500" style={{ fontVariationSettings: '"FILL" 1' }}>bolt</span>,
  sparkles: <span className="material-symbols-outlined text-yellow-400" style={{ fontVariationSettings: '"FILL" 1' }}>auto_awesome</span>,
  task: <span className="material-symbols-outlined text-indigo-600" style={{ fontVariationSettings: '"FILL" 1' }}>task</span>,
  event: <span className="material-symbols-outlined text-purple-600" style={{ fontVariationSettings: '"FILL" 1' }}>event</span>,
  smile: <span className="material-symbols-outlined text-orange-500" style={{ fontVariationSettings: '"FILL" 1' }}>sentiment_satisfied</span>,
};
